[project]
name = "polymarket-copy-trading-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "pandas>=3.0.0",
    "requests>=2.32.5",
]
